config/routes.rb
# inside config/routes.rb  
Rails.application.routes.draw do  
  root to: "home#index"
  
  resources :guests
  ## Unused Routes ##
  #get '/guests', to: "guests#index"
  #get "/guests/:id", to: "guests#list"
  #get "/home/index"  
    

end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
class Guest < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  
  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(article_params)

    if @guest.save
      redirect_to @guest
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])

    if @guest.update(article_params)
      redirect_to @guest
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:guest).permit(:name, :email)
    end
end

app/controllers/home_controller.rb
# inside app/controllers/home_controller.rb  
class HomeController < ApplicationController  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<section id="home-extended" class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= t :"Lauren_&_Dan" %></h1>
    <p class="leader-date">
      <%= t :Test %>, <%= t :Test %>

      <%= form_with model: guest do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% guest.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %><br>
    <% guest.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<form class="row g-3">
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Email</label>
    <input type="email" class="form-control" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Password</label>
    <input type="password" class="form-control" id="inputPassword4">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">City</label>
    <input type="text" class="form-control" id="inputCity">
  </div>
  <div class="col-md-4">
    <label for="inputState" class="form-label">State</label>
    <select id="inputState" class="form-select">
      <option selected>Choose...</option>
      <option>...</option>
    </select>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Zip</label>
    <input type="text" class="form-control" id="inputZip">
  </div>
  <div class="col-12">
      </label>
    </div>
  </div>
  <div class="col-12">
    <button type="submit" class="btn btn-primary">Sign in</button>
  </div>
</form>


    </p>
  </div>
</div>
</section

app/views/guests/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", guest: @guest %>

app/views/guests/index.html.erb
<h1>Guests#index</h1>


<ul>
  <% @guests.each do |guest| %>
    <li>
      <%= link_to guest.name, guest %>
    </li>
  <% end %>
</ul>

<%= link_to "New Guest", new_guest_path %>

app/views/guests/list.html.erb
<h1><%= @guest.name %></h1>

<p><%= @guest.email %></p>

app/views/guests/new.html.erb
<%= render "form", guest: @guest %>

app/views/guests/show.html.erb
<h1><%= @guest.name %></h1>

<p><%= @guest.email %></p>

<ul>
  <%= link_to "Edit", edit_guest_path(@guest) %>
  <%= link_to "Destroy", guest_path(@guest), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</ul>

app/views/home/_mid.html.erb
<section id="home-extended" class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= t :"Lauren_&_Dan" %></h1>
    <p class="leader-date">
      <%= t :Test %>, <%= t :Test %>
    </p>

<div class="btn-group" role="group" aria-label="Button group with nested dropdown">

  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary" data-bs-toggle="dropdown" aria-expanded="false">
      Welcome!
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <li><a class="dropdown-item" href=<%= "guests/new" %>>RSVP H!</a></li>
      <li><a class="dropdown-item" href=<%="guests"%>>Guest List</a></li>
    </ul>
  </div>
</div>
</section>

app/views/home/_top.erb
<section id="home" class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= t :"Lauren_&_Dan" %></h1>
    <p class="leader-date">
      <%= t :Test %>, <%= t :Test %>
    </p>
        <button type="button" 
                class="btn btn-lg btn-danger" 
                data-bs-toggle="popover" 
                title="Popover title" 
                data-bs-content="Amazing content, right ?">
                Click to toggle popover
        </button>
        <div class="btn-group">
	  <%= button_to "Guests", guests_path, :method => :get, class: "btn btn-primary btn-lg" %> 
                </button>
        </div>
</section>

app/views/home/index.html.erb
<!-- inside app/views/home/index.html.erb -->
<%= render partial: 'mid' %>
<%= render partial: 'top' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>